# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c492c2e1ef528180bea7b606d41adb28f9bf7fb71ce59a10d6a8e6a3cdcb4731697d774df705cdb2aeaf9645a035918f1f80f484f285e057e0fda4b9052600c7

test:
  secret_key_base: ea033a68ddd2d64d3cd0cb23d8e6ea5c13f63f2a015c13eb2358409aed79e1a0d1efbe74f8289e3aebacda270a1c61b8d931cf85b95e127511820715a4d0fd1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
